/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mobile;
import java.awt.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import lab01.Clases.ImagenFondoMovil;

/**
 *
 * @author gera
 */
public class Home extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    jDesktopPane2.setBorder(new ImagenFondoMovil());
            conn = Connect.ConnectBD();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tbLogin = new javax.swing.JTextField();
        tbPassword = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        FondoMovil = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/gera/Escritorio/titulomovil.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 290, 100);

        tbLogin.setText("User o Email");
        tbLogin.setToolTipText("User o Email");
        tbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLoginActionPerformed(evt);
            }
        });
        jPanel1.add(tbLogin);
        tbLogin.setBounds(70, 280, 190, 28);

        tbPassword.setText("Password");
        jPanel1.add(tbPassword);
        tbPassword.setBounds(70, 320, 190, 28);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(92, 380, 140, 30);

        FondoMovil.setIcon(new javax.swing.ImageIcon("/home/gera/Escritorio/mobile2.png")); // NOI18N
        jPanel1.add(FondoMovil);
        FondoMovil.setBounds(0, 0, 330, 660);
        jPanel1.add(jDesktopPane2);
        jDesktopPane2.setBounds(20, 70, 290, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLoginActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String sql = "select * from Usuarios where Usuario=? and Password=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, tbLogin.getText());
            pst.setString(2, tbPassword.getText());
            
            rs= pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Se conecto de la base");
            
            
                Prueba lista = new Prueba();
                jDesktopPane2.add(lista);
                lista.show();
            }
            else{
                JOptionPane.showMessageDialog(null, "No existe ese usuario");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMovil;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tbLogin;
    private javax.swing.JTextField tbPassword;
    // End of variables declaration//GEN-END:variables
}
