package Mobile;

import Mobile.Clases.Pedidos;
import Mobile.Controlador.Controlador;
import java.awt.Point;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class listaPedidos extends javax.swing.JInternalFrame {
//
    DefaultTableModel model;
//    ProxyPedido ICP;
//    ProxyUsuario ICU;
      Pedidos ped;
//    private ArrayList<DataPedido> listaPedidos;
      private Home h;
      
    public listaPedidos(Home h) {
        initComponents();
//        ICP = ProxyPedido.getInstance();
//          Controlador c = Controlador.getInstance();
        this.h=h;
        this.h.existeconexion();
        model = (DefaultTableModel)tblPedidos.getModel();
        CargarTabla();
//        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnSync = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(294, 298));
        setMinimumSize(new java.awt.Dimension(294, 298));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(294, 298));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Estado", "Cliente", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        jScrollPane2.setViewportView(jScrollPane1);

        btnSync.setText("Sincronizar");
        btnSync.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSyncMouseClicked(evt);
            }
        });
        btnSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyncActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnSync, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSync)
                    .addComponent(btnCerrarSesion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        Controlador c = Controlador.getInstance();
        String idPedido = null;
        long id = 0;
        JTable tab = (JTable)evt.getSource();
        Point point = evt.getPoint();
        int fila = tab.rowAtPoint(point);
        if(evt.getClickCount() == 1){
            idPedido = this.tblPedidos.getValueAt(fila,0).toString();
            id = Long.parseLong(idPedido);
            ped = c.getPedidoById(id);
            this.setVisible(false);
            detallePedido detallePed = new detallePedido(ped,h);
            detallePed.setLocation(0, 150);
            Home.jDesktopPane1.add(detallePed);
            detallePed.show();
        }
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void btnSyncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSyncMouseClicked
        Controlador c = Controlador.getInstance();
        c.syncEstados();
    }//GEN-LAST:event_btnSyncMouseClicked

    private void btnSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSyncActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Controlador c = Controlador.getInstance();
        c.cerrarSesion();
        this.setVisible(false);
        login l = new login(h);
        l.setLocation(40, 150);
        Home.jDesktopPane1.add(l);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    public void CargarTabla(){
        Controlador c = Controlador.getInstance();
        String lista[]=new String[5];
        c.getLstPedidos();
        for (Pedidos ped1 : c.getPeds()){
            String id = String.valueOf(ped1.getId());
            lista[0]= id;
            lista[1]= ped1.getEstado();
            lista[2]= ped1.getNickUsr();
            lista[3]= ped1.getDireccion();
            model.insertRow((int)tblPedidos.getRowCount(), lista);           
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnSync;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
